version: "2"
services:
  node:
    build: ./docker
    command: npm run docker
    volumes:
      - .:/usr/app/
      - ./node_modules:/usr/app/node_modules
    ports:
      - "89:80"
    environment:
      - NODE_ENV=production
